In [1]:
from pymongo import MongoClient

In [2]:
mongo = MongoClient()

In [3]:
data = list(mongo.data_3.events.find({},{"userid": 1, "jobId": 1}))

In [4]:
meta_data = list(mongo.data_3.data.find({},{"tag": 0, "_id": 0}))

In [5]:
meta_data[0]

{'jobId': 'Job_Fresher_Backend_Developer_other_Fresher_YY9HOS',
 'title': 'Fresher Backend Developer',
 'location': 'other',
 'skill': ['API', 'Backend', 'System', 'System', 'Java'],
 'salary': 785,
 'level': 'Fresher'}

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(data)

In [8]:
df.head()

_id                       userid  \
0  641957cff0faf23654da99f4     User_Junior_Backend_HN_2   
1  641957cff0faf23654da99f5  User_Fresher_Backend_HCM_87   
2  641957cff0faf23654da99f6    User_Junior_Backend_HN_22   
3  641957cff0faf23654da99f7  User_Fresher_Backend_HCM_54   
4  641957cff0faf23654da99f8   User_Junior_Backend_HCM_28   

                                               jobId  
0  Job_Fresher_Backend_Developer_other_Fresher_YY...  
1  Job_Fresher_Backend_Developer_other_Fresher_YY...  
2  Job_Fresher_Backend_Developer_other_Fresher_YY...  
3  Job_Fresher_Backend_Developer_other_Fresher_YY...  
4  Job_Fresher_Backend_Developer_other_Fresher_YY...

In [9]:
s = df.userid.value_counts()
s.where(s==1).dropna()

User_Fresher_Front-end_other_15    1.0
User_Leader_Data_other_30          1.0
User_Leader_Devops_other_28        1.0
User_Leader_Backend_other_30       1.0
User_Leader_Backend_other_28       1.0
                                  ... 
User_Fresher_Devops_HN_90          1.0
User_Middle_Backend_other_12       1.0
User_Fresher_Devops_other_33       1.0
User_Fresher_Devops_HN_80          1.0
User_Junior_Devops_other_30        1.0
Name: userid, Length: 828, dtype: float64

In [10]:
df_1 = df.groupby(["userid"]).aggregate({"jobId": list}).reset_index()

In [11]:
df_1["num_items"] = df_1.jobId.str.len()

In [12]:
df_1[df_1["num_items"] > 1]

userid  \
0          User_Fresher_Backend_DN_0   
1          User_Fresher_Backend_DN_1   
2         User_Fresher_Backend_DN_10   
3        User_Fresher_Backend_DN_100   
4         User_Fresher_Backend_DN_11   
...                              ...   
7312  User_Senior_Front-end_other_82   
7313  User_Senior_Front-end_other_83   
7314  User_Senior_Front-end_other_85   
7318   User_Senior_Front-end_other_9   
7323  User_Senior_Front-end_other_97   

                                                  jobId  num_items  
0     [Job_Fresher_Backend_Engineer_DN_Fresher_FL62T...          3  
1     [Job_Fresher_Devops_DN_Fresher_KMTANQ, Job_Fre...          2  
2     [Job_Fresher_Backend_Engineer_other_Fresher_U9...          2  
3     [Job_Fresher_Backend_Engineer_other_Fresher_QM...          5  
4     [Job_Fresher_Backend_Engineer_HN_Fresher_3JRIX...          2  
...                                                 ...        ...  
7312  [Job_Leader_Front-end_Developer_HCM_Leader_TS8...          2  
7313  [Job_Senior_Front-end_Engineer_HCM_Senior_723T...          3  
7314  [Job_Senior_Front-end_Developer_HN_Senior_DPYM...          2  
7318  [Job_Senior_Front-end_Engineer_other_Senior_KX...          2  
7323  [Job_Junior_Front-end_Developer_HCM_Junior_QBB...          2  

[6498 rows x 3 columns]

In [13]:
import itertools
from functools import reduce


def create_pair_items(lst_items):
    return list(itertools.combinations(lst_items, 2))

In [14]:
item_item_data = reduce(lambda x, y: x + y, list([create_pair_items(i) for i in df_1.jobId.values.tolist()]))

In [15]:
len(item_item_data)

201733

In [16]:
df_2 = pd.DataFrame(item_item_data, columns=["item1", "item2"])

In [17]:
df_2.head()

item1  \
0     Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
1     Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
2  Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV   
3               Job_Fresher_Devops_DN_Fresher_KMTANQ   
4  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   

                                               item2  
0  Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV  
1  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ  
2  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ  
3     Job_Fresher_Data_Engineer_other_Fresher_7CZYYC  
4    Job_Fresher_Backend_Developer_DN_Fresher_3JKXHO

In [18]:
meta_df = pd.DataFrame(meta_data)

In [19]:
df_2 = df_2.merge(meta_df, how="left", left_on="item1", right_on="jobId")
df_2 = df_2.merge(meta_df, how="left", left_on="item2", right_on="jobId", suffixes=("_item1", "_item2"))

In [20]:
df_2.head()

item1  \
0     Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
1     Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
2  Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV   
3               Job_Fresher_Devops_DN_Fresher_KMTANQ   
4  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   

                                               item2  \
0  Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV   
1  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   
2  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   
3     Job_Fresher_Data_Engineer_other_Fresher_7CZYYC   
4    Job_Fresher_Backend_Developer_DN_Fresher_3JKXHO   

                                         jobId_item1  \
0     Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
1     Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
2  Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV   
3               Job_Fresher_Devops_DN_Fresher_KMTANQ   
4  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   

                title_item1 location_item1  \
0  Fresher Backend Engineer             DN   
1  Fresher Backend Engineer             DN   
2  Fresher Backend Engineer          other   
3            Fresher Devops             DN   
4  Fresher Backend Engineer          other   

                                skill_item1  salary_item1 level_item1  \
0     [Backend, System, PHP, ReactJS, Java]           919     Fresher   
1     [Backend, System, PHP, ReactJS, Java]           919     Fresher   
2         [API, Backend, PHP, System, Java]           952     Fresher   
3            [Azure, Python, Aws, Aws, Aws]          1147     Fresher   
4  [Golang, Java, English, Golang, English]           972     Fresher   

                                         jobId_item2  \
0  Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV   
1  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   
2  Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ   
3     Job_Fresher_Data_Engineer_other_Fresher_7CZYYC   
4    Job_Fresher_Backend_Developer_DN_Fresher_3JKXHO   

                 title_item2 location_item2  \
0   Fresher Backend Engineer          other   
1   Fresher Backend Engineer          other   
2   Fresher Backend Engineer          other   
3      Fresher Data Engineer          other   
4  Fresher Backend Developer             DN   

                                         skill_item2  salary_item2 level_item2  
0                  [API, Backend, PHP, System, Java]           952     Fresher  
1           [Golang, Java, English, Golang, English]           972     Fresher  
2           [Golang, Java, English, Golang, English]           972     Fresher  
3  [Machine Learning, Spark, Java, HDFS, Data Eng...          1339     Fresher  
4      [Backend, ReactJS, ReactJS, ReactJS, ReactJS]          1164     Fresher

In [21]:
import os
import tempfile

%matplotlib inline
import matplotlib.pyplot as plt

import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

import tensorflow_recommenders as tfrs

plt.style.use('seaborn-whitegrid')

2023-03-23 17:38:54.892323: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/spark/miniconda3/envs/recommend/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_214645/2468769046.py:13: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-whitegrid')


In [22]:
tensor_slices = {
    "item1": df_2.item1.values.tolist(),
    "title_item1": df_2.title_item1.values.tolist(),
    "location_item1": df_2.location_item1.values.tolist(),
    "level_item1": df_2.level_item1.values.tolist(),
    "item2": df_2.item2.values.tolist(),
    "title_item2": df_2.title_item2.values.tolist(),
    "location_item2": df_2.location_item2.values.tolist(),
    "level_item2": df_2.level_item2.values.tolist(),
}

jobs = tf.data.Dataset.from_tensor_slices({
    "item2": meta_df.jobId.values.tolist(),
    "location_item2": meta_df.location.values.tolist(),
    "level_item2": meta_df.level.values.tolist(),
})

items = tf.data.Dataset.from_tensor_slices(tensor_slices)

2023-03-23 17:38:56.089870: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-23 17:38:56.121227: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-23 17:38:56.121393: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-23 17:38:56.122223: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorF

In [23]:
unique_items = np.unique(meta_df.jobId.values.tolist())
unique_location = np.unique(meta_df.location.values.tolist())
unique_level = np.unique(meta_df.level.values.tolist())

In [24]:
class Movie1Model(tf.keras.Model):

  def __init__(self):
    super().__init__()

    max_tokens = 10_000

    self.title_embedding = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
          vocabulary=unique_items,mask_token=None),
      tf.keras.layers.Embedding(len(unique_items) + 1, 32)
    ])
    self.location_embedding = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
          vocabulary=unique_location,mask_token=None),
      tf.keras.layers.Embedding(len(unique_location) + 1, 32)
    ])
    self.level_embedding = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
          vocabulary=unique_level,mask_token=None),
      tf.keras.layers.Embedding(len(unique_level) + 1, 32)
    ])

  def call(self, features):
    return tf.concat([
        self.title_embedding(features["item1"]),
        self.location_embedding(features["location_item1"]),
        self.level_embedding(features["level_item1"])
    ], axis=1)

class Movie2Model(tf.keras.Model):

  def __init__(self):
    super().__init__()

    max_tokens = 10_000

    self.title_embedding = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
          vocabulary=unique_items,mask_token=None),
      tf.keras.layers.Embedding(len(unique_items) + 1, 32)
    ])
    self.location_embedding = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
          vocabulary=unique_location,mask_token=None),
      tf.keras.layers.Embedding(len(unique_location) + 1, 32)
    ])
    self.level_embedding = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
          vocabulary=unique_level,mask_token=None),
      tf.keras.layers.Embedding(len(unique_level) + 1, 32)
    ])

  def call(self, features):
    return tf.concat([
        self.title_embedding(features["item2"]),
        self.location_embedding(features["location_item2"]),
        self.level_embedding(features["level_item2"])
    ], axis=1)

In [25]:
class MovielensModel(tfrs.Model):

  def __init__(self):
    super().__init__()
    self.movie_1_model: tf.keras.Model = Movie1Model()
    self.movie_2_model: tf.keras.Model = Movie2Model()
    self.task: tf.keras.layers.Layer = tfrs.tasks.Retrieval(
        metrics=tfrs.metrics.FactorizedTopK(
          candidates=jobs.batch(128).map(self.movie_2_model)
        )
    )

  def compute_loss(self, features, training=False) -> tf.Tensor:
    # We pick out the user features and pass them into the user model.
    movie_1_embeddings = self.movie_1_model(features)
    # And pick out the movie features and pass them into the movie model,
    # getting embeddings back.
    movie_2_embeddings = self.movie_2_model(features)

    # The task computes the loss and the metrics.
    return self.task(movie_1_embeddings, movie_2_embeddings)

In [26]:
model = MovielensModel()
model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))

In [27]:
tf.random.set_seed(42)
shuffled = items.shuffle(100_000, seed=42, reshuffle_each_iteration=False)

train = shuffled.take(80_000)
test = shuffled.skip(80_000).take(20_000)

cached_train = train.shuffle(100_000).batch(2048)
cached_test = test.batch(4096).cache()

In [28]:
model.fit(cached_train, epochs=3)

Epoch 1/3
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


2023-03-23 17:39:00.342209: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x7fb1a86d6350 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-03-23 17:39:00.342229: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 2070, Compute Capability 7.5
2023-03-23 17:39:00.344913: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-03-23 17:39:00.395393: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:00.427390: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled clust

 1/40 [..............................] - ETA: 1:35 - factorized_top_k/top_1_categorical_accuracy: 0.0029 - factorized_top_k/top_5_categorical_accuracy: 0.0127 - factorized_top_k/top_10_categorical_accuracy: 0.0337 - factorized_top_k/top_50_categorical_accuracy: 0.1709 - factorized_top_k/top_100_categorical_accuracy: 0.3267 - loss: 15610.9336 - regularization_loss: 0.0000e+00 - total_loss: 15610.9336

2023-03-23 17:39:00.612336: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:00.777542: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:00.782276: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-addr

 4/40 [==>...........................] - ETA: 3s - factorized_top_k/top_1_categorical_accuracy: 0.0103 - factorized_top_k/top_5_categorical_accuracy: 0.0543 - factorized_top_k/top_10_categorical_accuracy: 0.0946 - factorized_top_k/top_50_categorical_accuracy: 0.3152 - factorized_top_k/top_100_categorical_accuracy: 0.4989 - loss: 15065.0010 - regularization_loss: 0.0000e+00 - total_loss: 15065.0010

2023-03-23 17:39:00.874469: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:00.948021: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


 5/40 [==>...........................] - ETA: 3s - factorized_top_k/top_1_categorical_accuracy: 0.0139 - factorized_top_k/top_5_categorical_accuracy: 0.0642 - factorized_top_k/top_10_categorical_accuracy: 0.1095 - factorized_top_k/top_50_categorical_accuracy: 0.3457 - factorized_top_k/top_100_categorical_accuracy: 0.5300 - loss: 14885.7734 - regularization_loss: 0.0000e+00 - total_loss: 14885.7734

2023-03-23 17:39:01.101548: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:01.123854: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:01.205005: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-addr

10/40 [======>.......................] - ETA: 3s - factorized_top_k/top_1_categorical_accuracy: 0.0204 - factorized_top_k/top_5_categorical_accuracy: 0.0906 - factorized_top_k/top_10_categorical_accuracy: 0.1564 - factorized_top_k/top_50_categorical_accuracy: 0.4806 - factorized_top_k/top_100_categorical_accuracy: 0.6690 - loss: 14127.5548 - regularization_loss: 0.0000e+00 - total_loss: 14127.5548

2023-03-23 17:39:01.434358: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:01.435965: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:01.517292: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-addr

14/40 [=========>....................] - ETA: 2s - factorized_top_k/top_1_categorical_accuracy: 0.0222 - factorized_top_k/top_5_categorical_accuracy: 0.0984 - factorized_top_k/top_10_categorical_accuracy: 0.1732 - factorized_top_k/top_50_categorical_accuracy: 0.5449 - factorized_top_k/top_100_categorical_accuracy: 0.7330 - loss: 13712.9129 - regularization_loss: 0.0000e+00 - total_loss: 13712.9129

2023-03-23 17:39:01.755061: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:01.846829: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


17/40 [===========>..................] - ETA: 2s - factorized_top_k/top_1_categorical_accuracy: 0.0235 - factorized_top_k/top_5_categorical_accuracy: 0.1035 - factorized_top_k/top_10_categorical_accuracy: 0.1820 - factorized_top_k/top_50_categorical_accuracy: 0.5751 - factorized_top_k/top_100_categorical_accuracy: 0.7624 - loss: 13501.7152 - regularization_loss: 0.0000e+00 - total_loss: 13501.7152

2023-03-23 17:39:01.995190: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:02.018471: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


23/40 [================>.............] - ETA: 1s - factorized_top_k/top_1_categorical_accuracy: 0.0249 - factorized_top_k/top_5_categorical_accuracy: 0.1106 - factorized_top_k/top_10_categorical_accuracy: 0.1966 - factorized_top_k/top_50_categorical_accuracy: 0.6153 - factorized_top_k/top_100_categorical_accuracy: 0.8007 - loss: 13224.8690 - regularization_loss: 0.0000e+00 - total_loss: 13224.8690

2023-03-23 17:39:02.442138: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


30/40 [=====================>........] - ETA: 0s - factorized_top_k/top_1_categorical_accuracy: 0.0243 - factorized_top_k/top_5_categorical_accuracy: 0.1138 - factorized_top_k/top_10_categorical_accuracy: 0.2062 - factorized_top_k/top_50_categorical_accuracy: 0.6423 - factorized_top_k/top_100_categorical_accuracy: 0.8270 - loss: 13021.7966 - regularization_loss: 0.0000e+00 - total_loss: 13021.7966

2023-03-23 17:39:02.931643: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:03.080510: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


36/40 [==========================>...] - ETA: 0s - factorized_top_k/top_1_categorical_accuracy: 0.0232 - factorized_top_k/top_5_categorical_accuracy: 0.1157 - factorized_top_k/top_10_categorical_accuracy: 0.2115 - factorized_top_k/top_50_categorical_accuracy: 0.6566 - factorized_top_k/top_100_categorical_accuracy: 0.8407 - loss: 12911.4983 - regularization_loss: 0.0000e+00 - total_loss: 12911.4983

2023-03-23 17:39:03.360493: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


40/40 [==============================] - 6s 82ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0225 - factorized_top_k/top_5_categorical_accuracy: 0.1168 - factorized_top_k/top_10_categorical_accuracy: 0.2133 - factorized_top_k/top_50_categorical_accuracy: 0.6627 - factorized_top_k/top_100_categorical_accuracy: 0.8460 - loss: 12262.6873 - regularization_loss: 0.0000e+00 - total_loss: 12262.6873
Epoch 2/3


2023-03-23 17:39:03.730923: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:03.811295: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:03.884513: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-addr

10/40 [======>.......................] - ETA: 2s - factorized_top_k/top_1_categorical_accuracy: 0.0193 - factorized_top_k/top_5_categorical_accuracy: 0.1437 - factorized_top_k/top_10_categorical_accuracy: 0.2651 - factorized_top_k/top_50_categorical_accuracy: 0.7496 - factorized_top_k/top_100_categorical_accuracy: 0.9185 - loss: 12267.3222 - regularization_loss: 0.0000e+00 - total_loss: 12267.3222

2023-03-23 17:39:04.837071: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


20/40 [==============>...............] - ETA: 1s - factorized_top_k/top_1_categorical_accuracy: 0.0222 - factorized_top_k/top_5_categorical_accuracy: 0.1478 - factorized_top_k/top_10_categorical_accuracy: 0.2662 - factorized_top_k/top_50_categorical_accuracy: 0.7512 - factorized_top_k/top_100_categorical_accuracy: 0.9195 - loss: 12247.9079 - regularization_loss: 0.0000e+00 - total_loss: 12247.9079

2023-03-23 17:39:05.541503: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


31/40 [======================>.......] - ETA: 0s - factorized_top_k/top_1_categorical_accuracy: 0.0206 - factorized_top_k/top_5_categorical_accuracy: 0.1466 - factorized_top_k/top_10_categorical_accuracy: 0.2655 - factorized_top_k/top_50_categorical_accuracy: 0.7522 - factorized_top_k/top_100_categorical_accuracy: 0.9198 - loss: 12247.2173 - regularization_loss: 0.0000e+00 - total_loss: 12247.2173

2023-03-23 17:39:06.307571: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


39/40 [============================>.] - ETA: 0s - factorized_top_k/top_1_categorical_accuracy: 0.0205 - factorized_top_k/top_5_categorical_accuracy: 0.1461 - factorized_top_k/top_10_categorical_accuracy: 0.2658 - factorized_top_k/top_50_categorical_accuracy: 0.7525 - factorized_top_k/top_100_categorical_accuracy: 0.9201 - loss: 12243.6147 - regularization_loss: 0.0000e+00 - total_loss: 12243.6147

2023-03-23 17:39:06.921053: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:07.069139: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


40/40 [==============================] - 3s 72ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0205 - factorized_top_k/top_5_categorical_accuracy: 0.1462 - factorized_top_k/top_10_categorical_accuracy: 0.2657 - factorized_top_k/top_50_categorical_accuracy: 0.7525 - factorized_top_k/top_100_categorical_accuracy: 0.9201 - loss: 11665.9942 - regularization_loss: 0.0000e+00 - total_loss: 11665.9942
Epoch 3/3


2023-03-23 17:39:07.143215: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


28/40 [====================>.........] - ETA: 0s - factorized_top_k/top_1_categorical_accuracy: 0.0182 - factorized_top_k/top_5_categorical_accuracy: 0.1555 - factorized_top_k/top_10_categorical_accuracy: 0.2808 - factorized_top_k/top_50_categorical_accuracy: 0.7719 - factorized_top_k/top_100_categorical_accuracy: 0.9277 - loss: 12137.4922 - regularization_loss: 0.0000e+00 - total_loss: 12137.4922

2023-03-23 17:39:09.354482: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


40/40 [==============================] - 3s 71ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0175 - factorized_top_k/top_5_categorical_accuracy: 0.1541 - factorized_top_k/top_10_categorical_accuracy: 0.2794 - factorized_top_k/top_50_categorical_accuracy: 0.7703 - factorized_top_k/top_100_categorical_accuracy: 0.9261 - loss: 11574.1082 - regularization_loss: 0.0000e+00 - total_loss: 11574.1082


2023-03-23 17:39:10.327258: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-03-23 17:39:10.401616: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


In [29]:
# Create a model that takes in raw query features, and
index = tfrs.layers.factorized_top_k.BruteForce(model.movie_1_model, k=20)
# recommends movies out of the entire movies dataset.
index.index_from_dataset(
  jobs.batch(100).map(lambda x: (x["item2"], model.movie_2_model(x)))
)

In [30]:
for i in train.take(1):
    print(i)

{'item1': <tf.Tensor: shape=(), dtype=string, numpy=b'Job_Junior_Devops_HCM_Junior_GI4EKP'>, 'title_item1': <tf.Tensor: shape=(), dtype=string, numpy=b'Junior Devops'>, 'location_item1': <tf.Tensor: shape=(), dtype=string, numpy=b'HCM'>, 'level_item1': <tf.Tensor: shape=(), dtype=string, numpy=b'Junior'>, 'item2': <tf.Tensor: shape=(), dtype=string, numpy=b'Job_Junior_Devops_HCM_Junior_H6J1UT'>, 'title_item2': <tf.Tensor: shape=(), dtype=string, numpy=b'Junior Devops'>, 'location_item2': <tf.Tensor: shape=(), dtype=string, numpy=b'HCM'>, 'level_item2': <tf.Tensor: shape=(), dtype=string, numpy=b'Junior'>}


In [31]:
_, pred = index({"item1": np.array(["Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ"]),
                 "location_item1": np.array(["DN"]),
                 "level_item1": np.array(["Fresher"])
                })
pred.numpy()

array([[b'Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ',
        b'Job_Fresher_Backend_Engineer_other_Fresher_7L80C5',
        b'Job_Junior_Backend_Developer_DN_Junior_45JQQ2',
        b'Job_Fresher_Backend_Developer_DN_Fresher_3JKXHO',
        b'Job_Fresher_Backend_Engineer_other_Fresher_0AOC9I',
        b'Job_Junior_Backend_Developer_DN_Junior_2OOEQN',
        b'Job_Fresher_Backend_Developer_other_Fresher_6BH3Q5',
        b'Job_Fresher_Devops_DN_Fresher_KMTANQ',
        b'Job_Junior_Backend_Engineer_other_Junior_TVC2DO',
        b'Job_Fresher_Backend_Engineer_other_Fresher_7XN3IV',
        b'Job_Fresher_Backend_Engineer_other_Fresher_5EU5MS',
        b'Job_Fresher_Backend_Engineer_other_Fresher_UCXBIJ',
        b'Job_Fresher_Backend_Engineer_other_Fresher_9UEC0K',
        b'Job_Fresher_Backend_Developer_other_Fresher_HIVJ24',
        b'Job_Junior_Backend_Engineer_DN_Junior_MTBUHR',
        b'Job_Junior_Backend_Developer_other_Junior_CMV56I',
        b'Job_Fresher_Backend_Engineer_o

In [32]:
df_2[df_2["item1"]=="Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ"][["item1", "item2"]]

item1  \
0       Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
1       Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
25      Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
26      Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
27      Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
...                                                ...   
105221  Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
105429  Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
105430  Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
105431  Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   
105432  Job_Fresher_Backend_Engineer_DN_Fresher_FL62TZ   

                                                    item2  
0       Job_Fresher_Backend_Engineer_other_Fresher_F6SGNV  
1       Job_Fresher_Backend_Engineer_other_Fresher_U96NGQ  
25      Job_Fresher_Backend_Engineer_other_Fresher_7L80C5  
26        Job_Fresher_Backend_Developer_HN_Fresher_R0M5GA  
27      Job_Fresher_Backend_Engineer_other_Fresher_QME5O3  
...                                                   ...  
105221      Job_Middle_Backend_Developer_HN_Middle_V9L3C9  
105429   Job_Middle_Backend_Developer_other_Middle_D92DMR  
105430  Job_Fresher_Backend_Developer_other_Fresher_HI...  
105431    Job_Middle_Backend_Engineer_other_Middle_3MBKEK  
105432  Job_Fresher_Backend_Developer_other_Fresher_LZ...  

[477 rows x 2 columns]